//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net35WebForms.App_Code {
	
	
	public partial class WebForm1 {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox TextBox1;
		
		protected System.Web.UI.WebControls.TextBox TextBox2;
		
		protected System.Web.UI.WebControls.TextBox TextBox3;
		
		protected System.Web.UI.WebControls.DropDownList DropDownList1;
		
		protected System.Web.UI.WebControls.RadioButtonList RadioButtonList1;
		
		protected System.Web.UI.WebControls.TextBox TextBox4;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.WebControls.Label lblResult;
	}
}
